package com.pojo;
// Generated 30 Apr, 2018 4:01:54 PM by Hibernate Tools 3.5.0.Final

/**
 * Admin generated by hbm2java
 */
public class Admin implements java.io.Serializable {

	private Integer aid;
	private String username;
	private String apassword;
	private String aname;

	public Admin() {
	}

	public Admin(String username, String apassword, String aname) {
		this.username = username;
		this.apassword = apassword;
		this.aname = aname;
	}

	public Integer getAid() {
		return this.aid;
	}

	public void setAid(Integer aid) {
		this.aid = aid;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getApassword() {
		return this.apassword;
	}

	public void setApassword(String apassword) {
		this.apassword = apassword;
	}

	public String getAname() {
		return this.aname;
	}

	public void setAname(String aname) {
		this.aname = aname;
	}

	@Override
	public String toString() {
		return "Admin [aid=" + aid + ", username=" + username + ", apassword=" + apassword + ", aname=" + aname + "]";
	}
	

}
