package com.pojo;
// Generated 30 Apr, 2018 4:01:54 PM by Hibernate Tools 3.5.0.Final

/**
 * Cart generated by hbm2java
 */
public class Cart implements java.io.Serializable {

	private Integer cartid;
	private Register register;
	private Product product;
	private int totprice;
	private int cquantity;

	public Cart() {
	}

	public Cart(int totprice, int cquantity) {
		this.totprice = totprice;
		this.cquantity = cquantity;
	}

	public Cart(Register register, Product product, int totprice, int cquantity) {
		this.register = register;
		this.product = product;
		this.totprice = totprice;
		this.cquantity = cquantity;
	}

	public Integer getCartid() {
		return this.cartid;
	}

	public void setCartid(Integer cartid) {
		this.cartid = cartid;
	}

	public Register getRegister() {
		return this.register;
	}

	public void setRegister(Register register) {
		this.register = register;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public int getTotprice() {
		return this.totprice;
	}

	public void setTotprice(int totprice) {
		this.totprice = totprice;
	}

	public int getCquantity() {
		return this.cquantity;
	}

	public void setCquantity(int cquantity) {
		this.cquantity = cquantity;
	}

}
