package com.pojo;
// Generated 30 Apr, 2018 4:01:54 PM by Hibernate Tools 3.5.0.Final

/**
 * Contact generated by hbm2java
 */
public class Contact implements java.io.Serializable {

	private Integer cid;
	private String cname;
	private String cemail;
	private String comment;

	public Contact() {
	}

	public Contact(String cname, String cemail, String comment) {
		this.cname = cname;
		this.cemail = cemail;
		this.comment = comment;
	}

	public Integer getCid() {
		return this.cid;
	}

	public void setCid(Integer cid) {
		this.cid = cid;
	}

	public String getCname() {
		return this.cname;
	}

	public void setCname(String cname) {
		this.cname = cname;
	}

	public String getCemail() {
		return this.cemail;
	}

	public void setCemail(String cemail) {
		this.cemail = cemail;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

}
