package com.pojo;
// Generated 30 Apr, 2018 4:01:54 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * Demo generated by hbm2java
 */
public class Demo implements java.io.Serializable {

	private Integer did;
	private Register register;
	private Machinery machinery;
	private Date demodate;
	private String address;
	private String phone;

	public Demo() {
	}

	public Demo(Date demodate, String address, String phone) {
		this.demodate = demodate;
		this.address = address;
		this.phone = phone;
	}

	public Demo(Register register, Machinery machinery, Date demodate, String address, String phone) {
		this.register = register;
		this.machinery = machinery;
		this.demodate = demodate;
		this.address = address;
		this.phone = phone;
	}

	public Integer getDid() {
		return this.did;
	}

	public void setDid(Integer did) {
		this.did = did;
	}

	public Register getRegister() {
		return this.register;
	}

	public void setRegister(Register register) {
		this.register = register;
	}

	public Machinery getMachinery() {
		return this.machinery;
	}

	public void setMachinery(Machinery machinery) {
		this.machinery = machinery;
	}

	public Date getDemodate() {
		return this.demodate;
	}

	public void setDemodate(Date demodate) {
		this.demodate = demodate;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

}
