package com.pojo;
// Generated 30 Apr, 2018 4:01:54 PM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Producttype generated by hbm2java
 */
public class Producttype implements java.io.Serializable {

	private Integer tid;
	private String producttype;
	private Set products = new HashSet(0);

	public Producttype() {
	}

	public Producttype(String producttype) {
		this.producttype = producttype;
	}

	public Producttype(String producttype, Set products) {
		this.producttype = producttype;
		this.products = products;
	}

	public Integer getTid() {
		return this.tid;
	}

	public void setTid(Integer tid) {
		this.tid = tid;
	}

	public String getProducttype() {
		return this.producttype;
	}

	public void setProducttype(String producttype) {
		this.producttype = producttype;
	}

	public Set getProducts() {
		return this.products;
	}

	public void setProducts(Set products) {
		this.products = products;
	}

}
