package com.pojo;
// Generated 30 Apr, 2018 4:01:54 PM by Hibernate Tools 3.5.0.Final

import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product implements java.io.Serializable {

	private Integer pid;
	private Producttype producttype;
	private String pname;
	private String pdescription;
	private int price;
	private byte[] image;
	private int totquantity;
	private int totalprice;
	private Set carts = new HashSet(0);
	private Set purchases = new HashSet(0);

	public Product() {
	}

	public Product(Producttype producttype, String pname, String pdescription, int price, byte[] image, int totquantity,
			int totalprice) {
		this.producttype = producttype;
		this.pname = pname;
		this.pdescription = pdescription;
		this.price = price;
		this.image = image;
		this.totquantity = totquantity;
		this.totalprice = totalprice;
	}

	public Product(Producttype producttype, String pname, String pdescription, int price, byte[] image, int totquantity,
			int totalprice, Set carts, Set purchases) {
		this.producttype = producttype;
		this.pname = pname;
		this.pdescription = pdescription;
		this.price = price;
		this.image = image;
		this.totquantity = totquantity;
		this.totalprice = totalprice;
		this.carts = carts;
		this.purchases = purchases;
	}

	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	public Producttype getProducttype() {
		return this.producttype;
	}

	public void setProducttype(Producttype producttype) {
		this.producttype = producttype;
	}

	public String getPname() {
		return this.pname;
	}

	public void setPname(String pname) {
		this.pname = pname;
	}

	public String getPdescription() {
		return this.pdescription;
	}

	public void setPdescription(String pdescription) {
		this.pdescription = pdescription;
	}

	public int getPrice() {
		return this.price;
	}

	public void setPrice(int price) {
		this.price = price;
	}

	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

	public int getTotquantity() {
		return this.totquantity;
	}

	public void setTotquantity(int totquantity) {
		this.totquantity = totquantity;
	}

	public int getTotalprice() {
		return this.totalprice;
	}

	public void setTotalprice(int totalprice) {
		this.totalprice = totalprice;
	}

	public Set getCarts() {
		return this.carts;
	}

	public void setCarts(Set carts) {
		this.carts = carts;
	}

	public Set getPurchases() {
		return this.purchases;
	}

	public void setPurchases(Set purchases) {
		this.purchases = purchases;
	}

	@Override
	public String toString() {
		return "Product [pid=" + pid + ", producttype=" + producttype + ", pname=" + pname + ", pdescription="
				+ pdescription + ", price=" + price + ", image=" + Arrays.toString(image) + ", totquantity="
				+ totquantity + ", totalprice=" + totalprice + ", carts=" + carts + ", purchases=" + purchases + "]";
	}
	

}
