package com.pojo;
// Generated 30 Apr, 2018 4:01:54 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * Purchase generated by hbm2java
 */
public class Purchase implements java.io.Serializable {

	private Integer purid;
	private Register register;
	private Product product;
	private Date purdate;
	private String address;
	private String phone;
	private double totprice;
	private Integer pquantity;

	public Purchase() {
	}

	public Purchase(Date purdate, String address, String phone, double totprice, int pquantity) {
		this.purdate = purdate;
		this.address = address;
		this.phone = phone;
		this.totprice = totprice;
		this.pquantity=pquantity;
	}

	public Purchase(Register register, Product product, Date purdate, String address, String phone, double totprice, int pquantity) {
		this.register = register;
		this.product = product;
		this.purdate = purdate;
		this.address = address;
		this.phone = phone;
		this.totprice = totprice;
		this.pquantity=pquantity;
	}

	public Integer getPurid() {
		return this.purid;
	}

	public void setPurid(Integer purid) {
		this.purid = purid;
	}

	public Register getRegister() {
		return this.register;
	}

	public void setRegister(Register register) {
		this.register = register;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public Date getPurdate() {
		return this.purdate;
	}

	public void setPurdate(Date purdate) {
		this.purdate = purdate;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public double getTotprice() {
		return this.totprice;
	}

	public void setTotprice(double totprice) {
		this.totprice = totprice;
	}
	

	public Integer getPquantity() {
		return pquantity;
	}

	public void setPquantity(Integer pquantity) {
		this.pquantity = pquantity;
	}


}
