package com.pojo;
// Generated 30 Apr, 2018 4:01:54 PM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Register generated by hbm2java
 */
public class Register implements java.io.Serializable {

	private Integer id;
	private String name;
	private String email;
	private String password;
	private String phone;
	private String gender;
	private String address;
	private String state;
	private String city;
	private String pincode;
	private Set soiltests = new HashSet(0);
	private Set carts = new HashSet(0);
	private Set demos = new HashSet(0);
	private Set purchases = new HashSet(0);

	public Register() {
	}

	public Register(String name, String email, String password, String phone, String gender, String address,
			String state, String city, String pincode) {
		this.name = name;
		this.email = email;
		this.password = password;
		this.phone = phone;
		this.gender = gender;
		this.address = address;
		this.state = state;
		this.city = city;
		this.pincode = pincode;
	}

	public Register(String name, String email, String password, String phone, String gender, String address,
			String state, String city, String pincode, Set soiltests, Set carts, Set demos, Set purchases) {
		this.name = name;
		this.email = email;
		this.password = password;
		this.phone = phone;
		this.gender = gender;
		this.address = address;
		this.state = state;
		this.city = city;
		this.pincode = pincode;
		this.soiltests = soiltests;
		this.carts = carts;
		this.demos = demos;
		this.purchases = purchases;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getPincode() {
		return this.pincode;
	}

	public void setPincode(String pincode) {
		this.pincode = pincode;
	}

	public Set getSoiltests() {
		return this.soiltests;
	}

	public void setSoiltests(Set soiltests) {
		this.soiltests = soiltests;
	}

	public Set getCarts() {
		return this.carts;
	}

	public void setCarts(Set carts) {
		this.carts = carts;
	}

	public Set getDemos() {
		return this.demos;
	}

	public void setDemos(Set demos) {
		this.demos = demos;
	}

	public Set getPurchases() {
		return this.purchases;
	}

	public void setPurchases(Set purchases) {
		this.purchases = purchases;
	}

	@Override
	public String toString() {
		return "Register [id=" + id + ", name=" + name + ", email=" + email + ", password=" + password + ", phone="
				+ phone + ", gender=" + gender + ", address=" + address + ", state=" + state + ", city=" + city
				+ ", pincode=" + pincode + ", soiltests=" + soiltests + ", carts=" + carts + ", demos=" + demos
				+ ", purchases=" + purchases + "]";
	}
	

}
