package com.pojo;
// Generated 30 Apr, 2018 4:01:54 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * Soiltest generated by hbm2java
 */
public class Soiltest implements java.io.Serializable {

	private Integer stid;
	private Register register;
	private String address;
	private String phone;
	private String soiltype;
	private Date soildate;

	public Soiltest() {
	}

	public Soiltest(String address, String phone, String soiltype, Date soildate) {
		this.address = address;
		this.phone = phone;
		this.soiltype = soiltype;
		this.soildate = soildate;
	}

	public Soiltest(Register register, String address, String phone, String soiltype, Date soildate) {
		this.register = register;
		this.address = address;
		this.phone = phone;
		this.soiltype = soiltype;
		this.soildate = soildate;
	}

	public Integer getStid() {
		return this.stid;
	}

	public void setStid(Integer stid) {
		this.stid = stid;
	}

	public Register getRegister() {
		return this.register;
	}

	public void setRegister(Register register) {
		this.register = register;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getSoiltype() {
		return this.soiltype;
	}

	public void setSoiltype(String soiltype) {
		this.soiltype = soiltype;
	}

	public Date getSoildate() {
		return this.soildate;
	}

	public void setSoildate(Date soildate) {
		this.soildate = soildate;
	}

}
